site_name: QGIS.бг докс
repo_url: https://github.com/qgisbg/docs
extra_css:
  - assets/consent.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/cookies-eu-banner@2.0.1/dist/cookies-eu-banner.js
  - assets/consent.js
plugins:
  - awesome-pages: {}
  - search:
      lang:
        - ru
        - en
theme:
  language: bg
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: green
      accent: green
markdown_extensions:
  - smarty
  - markdown_captions
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.escapeall
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tilde
  - mdx_include
  - mdx_iconify:
      patterns:
        qgis:
          width: "36"
          height: "36"
          prefix: https://raw.githubusercontent.com/qgis/QGIS/master/images/themes/default/
          suffix: .svg
          check_suffix: True
  - toc:
      permalink: true
nav:
  - index.md
  - ... | wiki/*/*.md
  - ... | gisintro/*.md
  - ... | bgd/*.md
  - ... | meta/*.md
