site_name: QGIS.бг докс
language: bg
repo_url: https://github.com/qgisbg/docs
extra_css:
  - assets/consent.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/cookies-eu-banner@2.0.1/dist/cookies-eu-banner.js
  - assets/consent.js
plugins:
  - awesome-pages: {}
  - search:
      lang:
        - ru
        - en
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: green
      accent: green
markdown_extensions:
  - smarty
  - footnotes
  - markdown_captions
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - ...
