name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1

      - name: Upgrade pip
        run: sudo /usr/local/bin/python -m pip install --upgrade pip

      - name: Deploy docs
        uses: suricactus/mkdocs-deploy-gh-pages@master
        env:
          EXTRA_PACKAGES: build-base
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
